openapi: "3.0.0"
info:
  version: 1.0.0
  title: Banking User API
servers:
  - url: http://localhost:8585
tags:
  - name: Crear cliente
  - name: Consultar cliente
paths:
  /clients/personal:
    post:
      summary: Registrar un nuevo cliente personal
      operationId: createPerson
      tags:
        - Crear cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePersonRequest"
      responses:
        '201':
          description: Cliente persona registrada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientResponse"
  /clients/companies:
    post:
      summary: Registrar un nuevo cliente empresa
      operationId: createCompany
      tags:
        - Crear cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCompanyRequest"
      responses:
        '201':
          description: Cliente empresa registrada satisfactoriamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientResponse"
  /clients/{id}:
    get:
      summary: Obtener los datos del cliente
      operationId: getClientById
      tags:
        - Consultar cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del cliente
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientResponse"
        '404':
          description: Cliente no encontrado
components:
  schemas:
    AuditTrail:
      type: object
      description: Auditing metadata for entities
      properties:
        createdAt:
          type: string
          format: date-time
          example: "2025-05-18T14:00:00Z"
        createdBy:
          type: string
          example: "admin"
        updatedAt:
          type: string
          format: date-time
          example: "2025-05-18T15:00:00Z"
        updatedBy:
          type: string
          example: "admin"
    BasicInformation:
      type: object
      description: Common attributes for a person or company
      required:
        - name
        - email
        - phone
        - identifier
      properties:
        name:
          type: string
          example: "Juan Escurra"
        email:
          type: string
          format: email
          example: "juan@example.com"
        phone:
          type: string
          example: "987456321"
        identifier:
          type: string
          example: "12345678"
    CreateCompanyRequest:
      allOf:
        - $ref: '#/components/schemas/BasicInformation'
        - type: object
          description: Legal entity (company)
          required:
            - commercialName
            - fiscalAddress
            - representatives
          properties:
            category:
              type: string
              description: Categorías de cliente empresas
              default: STANDARD
              enum:
                - STANDARD
                - PYME
            name:
                type: string
                example: "Tech Solutions S.A.C."
            fiscalAddress:
              type: string
              example: "123 Main St, Lima"
            commercialName:
              type: string
              example: "Tech Solutions S.A.C."
            representatives:
                type: array
                items:
                    $ref: '#/components/schemas/CreatePersonRequest'

    CreatePersonRequest:
      allOf:
        - $ref: '#/components/schemas/BasicInformation'
        - type: object
          description: Natural person
          required:
            - lastname
            - identifierType
          properties:
            category:
              type: string
              description: Categorías del cliente individual
              default: STANDARD
              enum:
                - STANDARD
                - VIP
            lastname:
              type: string
              example: "Escurra"
            identifierType:
              $ref: '#/components/schemas/IdentifierType'
    ClientResponse:
      allOf:
        - $ref: '#/components/schemas/AuditTrail'
        - type: object
          description: Cliente empresarial o personal
          oneOf:
            - required: [person]
            - required: [company]
          properties:
            id:
              type: string
              example: "123456"
            clientType:
              $ref: '#/components/schemas/ClientType'
            active:
              type: boolean
              example: true
            person:
              $ref: '#/components/schemas/PersonResponse'
            company:
              $ref: '#/components/schemas/CompanyResponse'
    PersonResponse:
      allOf:
        - $ref: '#/components/schemas/AuditTrail'
        - $ref: '#/components/schemas/CreatePersonRequest'
        - type: object
          description: Persona o individuo registrado
          properties:
            id:
              type: string
    CompanyResponse:
      allOf:
        - $ref: '#/components/schemas/AuditTrail'
        - $ref: '#/components/schemas/BasicInformation'
        - type: object
          description: Empresa registrada
          properties:
            category:
              type: string
              description: Categorías de cliente empresas
              default: STANDARD
              enum:
                - STANDARD
                - PYME
            id:
              type: string
            name:
              type: string
              example: "Tech Solutions S.A.C."
            fiscalAddress:
              type: string
              example: "123 Main St, Lima"
            commercialName:
              type: string
              example: "Tech Solutions S.A.C."
    ClientType:
      type: string
      description: Type of the client
      enum:
        - PERSONAL
        - COMPANY
      example: PERSONAL

    ClientCategory:
      type: string
      description: Business classification of the client
      enum:
        - REGULAR
        - PREMIUM
        - ENTERPRISE
      example: PREMIUM
    IdentifierType:
      type: string
      description: Type of identifier
      enum:
        - DNI
        - PASSPORT
      example: "DNI"